# Generated by Django 3.2.8 on 2021-12-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='shoe_pics')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('quantity', models.BigIntegerField()),
                ('contact_number', models.BigIntegerField()),
                ('order_itemid', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default='Pending')),
            ],
        ),
        migrations.CreateModel(
            name='OTPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpcurrent', models.TextField()),
                ('emailotp', models.CharField(max_length=200)),
                ('otp_expire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
