# Generated by Django 3.2.8 on 2021-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
