# Generated by Django 3.2.8 on 2021-12-09 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0002_otps'),
    ]

    operations = [
        migrations.AddField(
            model_name='otps',
            name='otp_expire',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
