# Generated by Django 3.2.8 on 2021-11-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0003_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
